#:schema node_modules/wrangler/config-schema.json
name = "zibi-sublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "b6d6acc0bdea4f51a8ef2a0befd69335" }
]

[assets]
directory = "./public"
